[theme]
base = "light"
primaryColor = "#1265AB"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#16324F"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
